### ISSUE TITLE
Infinite recompiling

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Script-Recompiler#9]
DRGN21/621/3 is running infinitely trying to recompile. No error registering.

**Comment by LordMonoxide** [comment]
Not happening with current code, can you confirm?

**Comment by theflyingzamboni** [comment]
It seems to be something that happens when I'm batching them, but I'm not sure what.

**Comment by theflyingzamboni** [comment]
Figured it out. It's not the batcher, I guess maybe you just fixed whatever was happening in 621/3. Try 291/3. The issue is that it goes into the PointerTable condition, but rel.labels is empty. So it skips the inner loop, decrements entryIndex, then the outer loop re-increments entryIndex.

**Comment by LordMonoxide** [comment]
291/3 is actually bugged. Converted exception to warning. de240b9
